### ISSUE TITLE
Starting a new project

### ISSUE THREAD

**Issue by jogu** [Mr-Dave/motion#115]
Hi MrDave,

As per discussion on the motion devel list ( https://sourceforge.net/p/motion/mailman/motion-devel/thread/4BD74F3F-75F3-40D2-AF88-CD65D16F400B%40heenan.me.uk/#msg35253241
 ), creating an issue to avoid inappropriate discussion on the motion list.

As mentioned/implied on the list, I'm happy to contribute where I can to a new project, the areas I can offer assistance that immediately spring to mind: working on the code myself, reviewing contributions from other people, helping get the new project setup on github etc, providing web hosting if necessary.

Thanks

Joseph

**Comment by tosiara** [comment]
I'm in :)

**Comment by ccrisan** [comment]
Count me in too. Given that my projects ([motionEye](https://github.com/ccrisan/motioneye) and [motionEyeOS](https://github.com/ccrisan/motioneyeos)) rely on the motion daemon, I would be more than happy to see it evolving into a new, community-maintained project, here on github.

I cannot promise to contribute with much code to the project itself, but I can provide some serious *beta testing* coming from all motionEye(OS) users.

**Comment by lvecsey** [comment]
I wonder if anyone here can look at the Cinelerra project, specifically their use of MPEG4 splicing. I was thinking motion could benefit from a similar technique. The idea would be to capture native MPEG4 (not MJPEG) series of frames, and then splice sequences together end-to-end so that there is a single longer movie file of activity.

**Comment by Mr-Dave** [comment]
As I mentioned on the other list, since there hasn't been any acceptance (or formal rejection) of the changes proposed it seems the only option to get a functional application to normal users is to create a new project that the distributors can take.  If the official maintainers of the Motion project start accepting changes, I'll consider merging back into it if asked.  For the new project, there is going to be a material amount of logistics to address before new code changes/fixes revisions are added.  The main objectives/milestones I see right now are:
1.  Use the 3.4.1 rc01 code branch as is with only changes that the packagers require
2.  New application name and version number in the code
3.  Update the manual and guide.
4.  Recreate all the deb packages.
5.  Identify location for a home page to have the guide and packages available (I research more but am currently thinking of sourceforge.  Github is good for the code but probably not for debs, rpms, tarballs and guide)
6.  User/Developer mailing list creation.
7.  Determine how to maintain existing branches that people are currently using while transitioning to new application.  
8. etc.

After the code set for 3.4.1 gets into the distributors chain for inclusion, then start addressing the additional enhancements and fixes.   As of right now, I am unsure as to how the repo and branches will work during the transition.  The historic branch process flow of Pull Request-> Unstable-> Master-> Release may need to be revised.  

If there are suggested names, lets hear them!

**Comment by marktheunissen** [comment]
>  Github is good for the code but probably not for debs, rpms, tarballs and guide)

Github has an excellent "releases" section and can distribute all those binaries with ease, as well as very good wiki functionality. Sourceforge has gone really far downhill... search for the spyware and adware scandals. E.g. http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/

**Comment by jogu** [comment]
Mr-Dave, this all sounds good.

For 5, I think I would stay away from sourceforge - like marktheunissen says, we should hopefully be able to do it all on github. I can help setting that up.

6 sounds good; I think I'd go for google groups for hosting the lists. We could also consider http://www.discourse.org, particularly for the user list, it could be consider modern and friendly. [discourse will require hosting/setup; I'm confidence that can be solved so lets focus any discussion on whether it's a better/worse experience for users / developers / the people helping].

7 I don't know how much we need to worry about this; I'd expect other people's repos can just be rebased on top of the new one. I've found git usually handles that quite well, even if files have been renamed/moved.


On suggested names, I don't have any great ideas - we may want to "motion" in there, so a few that come to mind:

MotionDaemon
MotionCam
MotionLens

(These seem fairly okay in terms of not conflicting too badly with anything else when you google for them.)


I'm a huge fan of very simple branching strategies where almost everything happens on master, and they seem to be popular on github. In that model, release branches are only created when we think we're ready to release, and are short lived only containing critical bug fixes. Development branches are only taken for a specific change and only when there's a need to collaboratively break things or experiment. Master is viewed as "always ready to ship" (but may have unknown bugs); ie. if a change is made that needs a man page / guide update, the change includes the updates to the docs (as opposed to trying to update the man page / guide at release time).

**Comment by infinity0** [comment]
Thanks for letting me know! I support this move. I'd also like to suggest a few alternatives that might save time:

1. Explicitly ask the official motion "maintainers" to take over their project, since they don't seem able to take care of their expected responsibilities.
2. Call your new forked project motion-ng, and just keep all the binary names etc as "motion". I can't see a use-case where anyone would reasonably want to install motion and motion-ng at the same time, so this would be perfectly fine from a distro's perspective.

**Comment by tosiara** [comment]
I also would vote to name new project `motion4` or `motion-ng` and remain binary name for compatibility

**Comment by Mr-Dave** [comment]
I have formally submitted the request to Kenneth and included the motion-devl mailing list.  While we wait to see the response, I am going to create a few new issues on here to track and discuss the various items that need to be addressed that we've mentioned above.  I think that it will be better to keep them isolated so that we can keep on topic.

**Comment by tosiara** [comment]
Reading Kenneth's answer and it looks like nothing has changed since 2014 (https://sourceforge.net/p/motion/mailman/message/32907411/).

So I believe the best option is to start a new project and if someone wants to maintain the older "official" motion, he could merge code into SVN, maintain Foswiki and so on. Once upon a time I have spent some time to prepare patches for SVN (https://github.com/tosiara/motion-svn-patchwork), but nobody really cared. And now have very limited motivation to spend any more efforts on a version that is about to die

Let's go ahead and create a new Github project and make it popular again

**Comment by jogu** [comment]
I'm very happy to see a response from Kenneth. As I read the new response (and I'd never seen the 2014 discussion, thanks for the link tosiara) Kenneth is willing to hand over the reigns but would like us to commit to using the existing foswiki and getting/keeping the documentation up to date, and to appoint a new leader.

I think we could probably find a way to make that work. Kenneth now seems happy that we still move to github etc as above. How do others feel?

**Comment by Mr-Dave** [comment]
I too was glad and surprised to see the response. I am going to do my best to make it work since I think it is the best solution for everyone.  I do agree with Ken on needing to keep the documentation up to date but have had many difficulties with that foswiki.  I would note to everyone that the motion guide.html and manual that are included in this repo IS updated and accurate.  Right now, I am going to close this issue and move forward with working on the planning for transition.  The planning list that I created last year is here for everyones reference.  Once I have a better handle on the plan, I'll open associated issues here for tracking.  If you review the list and see glaring omissions, please open an issue here so we can track it/work it to completion.  Thanks.

http://www.lavrsen.dk/foswiki/pub/Motion/PatchworkForNewRelease/TaskList.ods

**Comment by tosiara** [comment]
I'd rather keep this item open until the transition is really made.
