### ISSUE TITLE
Quality of captured movies.

### ISSUE THREAD

**Issue by jonathanbower** [Mr-Dave/motion#64]
Hi,
When capturing (recording) movies, the quality start out fine, but within 3-4 seconds the quality decreases down to unusable. It does not happen with the sackmotion/master branch. I've tested both rtsp and mjpeg streams. With debug in can see this, maybe related?
```
[1] [INF] [ENC] ffmpeg_avcodec_log: AVFrame.format is not set
 - flag 24
[1] [INF] [ENC] ffmpeg_avcodec_log: AVFrame.width or height is not set
 - flag 24
[1] [INF] [ENC] ffmpeg_avcodec_log: Statistics: 10 seeks, 31 writeouts
 - flag 48
```
Ideas?

**Comment by tosiara** [comment]
Do you get "pixelated" video?
Try increasing `ffmpeg_bps`, does it affect quality?

**Comment by jonathanbower** [comment]
Yes extremely pixelated, I tried different `ffmpeg_bps` values but there was no noticeable change. The strange thing is that the first few frames has good quality, then it deteriorates.

**Comment by tosiara** [comment]
I have seen such issue with `timelapse`. But increased `ffmpeg_bps` bitrate twice - and that resolved issue.
Are you using same ffmpeg vesrion across your two motion versions?

**Comment by tosiara** [comment]
There was also discussion on mail list: http://sourceforge.net/p/motion/mailman/message/33270388/

**Comment by jonathanbower** [comment]
Interesting, yes I have exactly the same problem as discussed in the list. I tried the extpie suggestion but i also get broken pipe, no output from x264 command:
`x264 - --input-res 640x480 --fps 15 --bitrate 6000 --preset ultrafast --quiet -o /tmp/out.mp4`

both x264 and ffmpeg are latest from master.

**Comment by tosiara** [comment]
Ok, so when you run the command just in console:
```
x264 - --input-res 640x480 --fps 15 --bitrate 6000 --preset ultrafast --quiet -o /tmp/out.mp4
```
What do you get?
Does it exit immediately or hangs waiting for data to read from stdin?

**Comment by jonathanbower** [comment]
Exits immediately, weird enough.

**Comment by tosiara** [comment]
This is probably because your xčšė is compiled without MP4 support. Paste here your ` x264 --help`

**Comment by jonathanbower** [comment]
http://pastebin.com/yqnDACKm

**Comment by tosiara** [comment]
Look at "(no)"
` .mp4 -> MP4 if compiled with GPAC or L-SMASH support (no)`
So there is no MP4 support in your x264. Try to compile your own or find other package for your OS.

**Comment by jonathanbower** [comment]
Beautiful. I installed libgpac-dev and recompiled x264. No i get a really crisp video. Thanks again!

**Comment by tosiara** [comment]
Thanks for sharing this!
I will also reply to the mail thread and let know about your solution

**Comment by chris1705** [comment]
I have exactly the same issue. I have installed libgpac-dev and recompiled the latest master of x264. The output of ./configure looks like this:

    ./configure --enable-shared --disable-opencl
    platform:      X86_64
    byte order:    little-endian
    system:        LINUX
    cli:           yes
    libx264:       internal
    shared:        yes
    static:        no
    asm:           yes
    interlaced:    yes
    avs:           avxsynth
    lavf:          yes
    ffms:          no
    mp4:           gpac
    gpl:           yes
    thread:        posix
    opencl:        no
    filters:       resize crop select_every 
    debug:         no
    gprof:         no
    strip:         no
    PIC:           yes
    bit depth:     8
    chroma format: all 

The output of x264 --help:

    x264 --help
    x264 core:148 r2579 73ae2d1
    Syntax: x264 [options] -o outfile infile

    Infile can be raw (in which case resolution is required),
      or YUV4MPEG (*.y4m),
      or Avisynth if compiled with support (yes).
      or libav* formats if compiled with lavf support (yes) or ffms support (no).
    Outfile type is selected by filename:
     .264 -> Raw bytestream
     .mkv -> Matroska
     .flv -> Flash Video
     .mp4 -> MP4 if compiled with GPAC or L-SMASH support (gpac)
    Output bit depth: 8 (configured at compile time)

Has someone an idea?

Thanks!

**Comment by Mr-Dave** [comment]
Wow, I have never seen it perform this poorly.  Can you provide the following so I can attempt to recreate on one of my machines and cameras?  Linux distribution/platform/version.  Libav or FFMpeg, where it was obtained and date/version  Camera capabilities (FPS/resolution/webcam or IP/how its setup). The complete configuration for Motion.  The version/commit that is being used for Motion.  Any indications whether the CPU is being maxed.  Using a level of NTC, a output of Motion during startup as well as when it is creating the mp4.

**Comment by DejavuDmitry** [comment]
The same problem on my motion... I Will present some information next monday.

**Comment by Mr-Dave** [comment]
Think I may have found it.  When I revised the ffmpeg module, the gop_size was not specified correctly.  Below is the contents of a diff file that I'm hoping one of you can try to determine whether it resolves the issue.  (You can also just edit the ffmpeg.c code directly at line 275 to specify a gop_size=12 instead of 0)
```
diff --git a/ffmpeg.c b/ffmpeg.c
index febe41e..2c2505c 100644
--- a/ffmpeg.c
+++ b/ffmpeg.c
@@ -272,7 +272,7 @@ struct ffmpeg *ffmpeg_open(char *ffmpeg_video_codec, char *filename,
     c->height     = height;
     c->time_base.num = 1;
     c->time_base.den = rate;
-    c->gop_size   = 0;
+    c->gop_size   = 12;
     c->pix_fmt    = PIX_FMT_YUV420P;
     c->max_b_frames = 0;
```

**Comment by chris1705** [comment]
Thanks for you super quick answer! I have tried to set the `gop_size = 12` but it does only help a little: It now just takes a little longer until the quality becomes bad.

I use Ubuntu 14.04.01 Server (`Linux zbox 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`).

I have fetched the latest master of ffmpeg from git://source.ffmpeg.org/ffmpeg.git on the 14th August. I have used the version after the 5c6f4be9e60a5115989b1cf34e14ea7c826bfa8e commit.

**Configurations:**
* [ffmpeg output](http://pastebin.com/NDnvxm8d)
* [motion.conf](http://pastebin.com/KDmyuJvY)
* [thread1.conf](http://pastebin.com/u2kYAJi5)

My camera is a Amovison Q630M (Resolution: 1280x720; Bitrate 2048; Variable bitrate is set to true; Iframe Gap 25). ffmpeg tells the following about the stream:

    Input #0, rtsp, from 'rtsp://192.168.178.201/11':
      Metadata:
        title           : \11
      Duration: N/A, start: 0.057250, bitrate: N/A
        Stream #0:0: Video: h264 (Main), yuv420p, 1280x720, 5 tbr, 90k tbn, 180k tbc
        Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s 

Is there a way making records without reencoding the video stream, because it already cames encoded as h264? Or is the transcoding necessary for motion?

For 24/7 recording I have always used ffmpeg with `-vcodec copy`...

Thank you!

**Comment by Mr-Dave** [comment]
Good to see the edit.  I believe you could also turn on the variable bit rate within the Motion parms.  Can others validate the change resolves the issue before I start updating code and closing the issue?
  
On the other question of recording without re-encoding.  Since Motion must decode the stream to do its work, any pictures coming out must be re-encoded.  Motion can however be setup to monitor either of the streams on that camera and then when motion is detected, call a script via the on_event_start that captures the HD stream directly without going through Motion.    When recording directly via ffmpeg/avconv, make sure to add the parameter ```-rtsp_transport tcp``` otherwise the quality will suffer.  The following is a snippet of a script that records 30 seconds without re-encoding ```ffmpeg -rtsp_transport tcp -i $NETCAMURL -c copy -t 30 $OUTPUTFILE1```

**Comment by Mr-Dave** [comment]
Issue being closed:  An additional item may be to make sure that if it is a variable bit rate camera, ensure that the option is selected in the ffmpeg section of the motion.conf file.
