### ISSUE TITLE
 capturing thrown objects

### ISSUE THREAD

**Issue by keikurono** [Mr-Dave/motion#83]
Hi Mr-Dave.
I want to catch thrown objects.
I have 'threshold 12' and yet we fail to capture these thrown objects (I use "mask_file" correctly).  Also I have "minimum_motion_frames 1". I capture images with rtsp at ~ 30 FPS. All good. 
Maybe I need to better configure the noise? (I have it with "noise_level 32").
My conf: http://pastebin.com/raw.php?i=F3d5pGUz

**Comment by Mr-Dave** [comment]
I am not sure I'm following the question or issue so let me try to summarize what I think you are indicating.  

You have a camera set up via rtsp, it is pointing at some wide field, you've implemented a masking file to only look at a certain section of the picture, and within the area designated for detection, you are trying to catch an event in which something (lets say a football) is thrown across the field of view of the detection area.

What you are experiencing is that the ball is going across the detection area but that no event is triggered?  No movie captured?  No pictures taken?  

Is this an accurate summarization?

**Comment by keikurono** [comment]
Yes.
*I just captured video, photos this off.
At night is the problem. It does not capture any movement of the ball.
It is possible only in the day, catch the ball.
I change the "threshold 12" to "threshold 4", in a few hours I test.

**Comment by Mr-Dave** [comment]
This may be more of a question for the user forum rather than here which I think of as code problems.  Since it works during the day but not at night, it sounds like it would be a threshold parameter issue.  You could also try making sure that the parameters related to noise are turned off and maybe the despeckle.  I haven't used those parameters so I can not tell you how much they change detection between day and night.  (Other users may have more insights)
